mainapp/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', index, name='home'),
    path('about/', about, name='about'),

    path('dariler/', dariler, name='dariler'),
    path('dariler/<slug:slug>/', daridetails, name='daridetails'),
    path('dariler/create', dari_create, name='dari-create'),
    path('dariler/adddari', adddari, name='adddari'),
    path('dariler/<slug:slug>/delete', DariDeleteView.as_view(), name='dariler-delete'),
    path('dariler/<slug:slug>/update', DariUpdateView.as_view(), name='dariler-update'),

    path('scientists/', scientists, name='scientists'),
    path('scientists/<slug:slug>/', scientistsdetails, name='scientistsdetails'),
    path('scientists/<slug:slug>/delete', ScientistsDeleteView.as_view(), name='scientists-delete'),
    path('scientists/create', scientist_create, name='scientist-create'),
    path('scientists/<slug:slug>/update', ScientistsUpdateView.as_view(), name='scientists-update'),

    path('scientist_or_dari', scientist_or_dari, name='scientist_or_dari'),
    path('contact/', contact, name='contact'),
    path("addreview/", addreview, name="addreview"),
]

med/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('accounts/', include('allauth.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/models.py
from django.db import models


class Tur(models.Model):
    name = models.CharField('Аты', max_length=255)

    class Meta:
        db_table = 'tur'
        verbose_name = "Дәрі шөп түрі"
        verbose_name_plural = "Дәрі шөп түрлері"

    def __str__(self):
        return self.name


class Scientists(models.Model):
    name = models.CharField('Аты', max_length=255)
    surname = models.CharField('Тегі', max_length=255)
    lauazym = models.CharField('Лауазымы', max_length=255)
    ainalasu_salasy = models.CharField('Айналысу саласы', max_length=255)
    slug = models.SlugField()
    dariler = models.ManyToManyField('DariShopter', verbose_name='Зерттеген дәрілер', related_name='dari', blank=True)
    image = models.ImageField('Сурет', upload_to='scientists/', null=True, blank=True)

    class Meta:
        db_table = 'scientists'
        verbose_name = "Ғалым"
        verbose_name_plural = "Ғалымдар"

    def __str__(self):
        return f"{self.name} - {self.surname} - {self.lauazym}"


class Laboratory(models.Model):
    name = models.CharField('Аты', max_length=255)
    director = models.CharField('Директоры', max_length=255)
    mamandar_sany = models.IntegerField('Мамандар саны')
    created_at = models.DateField('Құрылған уақыты')
    slug = models.SlugField()
    image = models.ImageField('Сурет', upload_to='laboratory/', null=True, blank=True)

    class Meta:
        db_table = 'laboratory'
        verbose_name = "Зертхана"
        verbose_name_plural = "Зертханалар"

    def __str__(self):
        return f"{self.name} - {self.director} - {self.created_at}"


class Region(models.Model):
    name = models.CharField('Облыс', max_length=255)
    district = models.CharField('Аудан', max_length=255)
    tau_aty = models.CharField('Тау аты', max_length=255, null=True, blank=True)
    qoryq_aty = models.CharField('Қорық аты', max_length=255, null=True, blank=True)
    laboratory = models.ForeignKey(Laboratory, on_delete=models.CASCADE, verbose_name='Жауапты зертхана', null=True,
                                   blank=True)
    slug = models.SlugField()

    class Meta:
        db_table = 'region'
        verbose_name = "Аумақ"
        verbose_name_plural = "Аумақтар"

    def __str__(self):
        return f"{self.name} - {self.district} - {self.tau_aty} - {self.qoryq_aty}"


class DariShopter(models.Model):
    name = models.CharField('Аты', max_length=255)
    type = models.ForeignKey(Tur, on_delete=models.CASCADE, verbose_name='Түрі')
    anyqtama = models.TextField('Анықтама', null=True, blank=True)
    description = models.TextField('Сипаттамасы')
    qoldanui = models.TextField('Қолдануы')
    count = models.IntegerField('Саны')
    scientists = models.ManyToManyField(Scientists, verbose_name='Зерттеуші ғалымдар')
    region = models.ForeignKey(Region, on_delete=models.CASCADE, verbose_name='Таралуы')
    image = models.ImageField('Сурет', upload_to='darishopter/', blank=True, null=True)
    created_at = models.DateTimeField('Жарияланған күні', auto_now_add=True)
    slug = models.SlugField()

    class Meta:
        db_table = 'darishopter'
        verbose_name = "Дәрі шөп"
        verbose_name_plural = "Дәрі шөптер"

    def __str__(self):
        return f"{self.name} - {self.type} - {self.count}"


class Reviews(models.Model):
    name = models.CharField("Есімі", max_length=100)
    title = models.CharField("Тақырыбы", max_length=100)
    email = models.EmailField()
    text = models.TextField("Хабарлама", max_length=5000)
    publish = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} - {self.email}"

    class Meta:
        db_table = 'reviews'
        verbose_name = "Пікір"
        verbose_name_plural = "Пікірлер"

mainapp/forms.py
from django import forms
from .models import Reviews, DariShopter, Scientists


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Reviews
        fields = ("name", "title", "email", "text")
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control border", "placeholder": "Есіміңіз"}),
            "title": forms.TextInput(attrs={"class": "form-control border", "placeholder": "Тақырыбы"}),
            "email": forms.EmailInput(attrs={"class": "form-control border", "placeholder": "Почтаңыз"}),
            "text": forms.Textarea(attrs={"class": "form-control border", "placeholder": "Хабарлама..."}),

        }


class DariShopterForm(forms.ModelForm):
    class Meta:
        model = DariShopter
        fields = (
            "name", "type", "anyqtama", "description", 'qoldanui', 'count', 'scientists', 'region', 'image', 'slug'
        )
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control border", "placeholder": "Дәрішөп аты"}),
            "anyqtama": forms.Textarea(attrs={"class": "form-control border", "placeholder": "Анықтама"}),
            "description": forms.Textarea(attrs={"class": "form-control border", "placeholder": "Сипаттамасы"}),
            "qoldanui": forms.Textarea(attrs={"class": "form-control border", "placeholder": "Қолдануы"}),
            "slug": forms.TextInput(attrs={"class": "form-control border", "placeholder": "Slug"}),
        }


class ScientistsForm(forms.ModelForm):
    class Meta:
        model = Scientists
        fields = ("name", "surname", "lauazym", "ainalasu_salasy", 'dariler', 'image', 'slug')
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control border", "placeholder": "Есімі"}),
            "surname": forms.TextInput(attrs={"class": "form-control border", "placeholder": "Тегі"}),
            "lauazym": forms.TextInput(attrs={"class": "form-control border", "placeholder": "Лауазымы"}),
            "slug": forms.TextInput(attrs={"class": "form-control border", "placeholder": "Slug"}),
            "ainalasu_salasy": forms.TextInput(
                attrs={"class": "form-control border", "placeholder": "Айналысу саласы"}),

        }

mainapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import ReviewForm, DariShopterForm, ScientistsForm
from .models import DariShopter, Scientists
from django.views.generic import DeleteView, UpdateView


def index(request):
    context = {'title': 'Басты бет'}
    return render(request, 'mainapp/index.html', context)


def about(request):
    context = {'title': 'Біз туралы'}
    return render(request, 'mainapp/about.html', context)


def dariler(request):
    dariler = DariShopter.objects.all()
    context = {'title': 'Дәрішөптер', 'dariler': dariler}
    return render(request, 'mainapp/dariler.html', context)


def daridetails(request, slug):
    question = get_object_or_404(DariShopter, slug=slug)
    context = {'dari': question, 'title': question.name}
    return render(request, 'mainapp/daridetails.html', context)


def dari_create(request):
    form = DariShopterForm()
    context = {
        'form': form,
    }
    return render(request, 'mainapp/dari_create.html', context)


def adddari(request):
    if request.method == 'POST':
        form = DariShopterForm(request.POST)
        if form.is_valid():

            form = form.save(commit=False)
            form.save()
            return redirect('dariler')


class DariDeleteView(DeleteView):
    model = DariShopter
    template_name = 'mainapp/dariler-delete.html'
    success_url = '/dariler/'


class DariUpdateView(UpdateView):
    model = DariShopter
    template_name = 'mainapp/dari_create.html'
    form_class = DariShopterForm


def scientists(request):
    scientists = Scientists.objects.all()
    context = {'title': 'Ғалымдар', 'scientists': scientists}
    return render(request, 'mainapp/scientists.html', context)


def scientist_create(request):
    if request.method == 'POST':
        form = ScientistsForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('scientists')

    form = ScientistsForm()
    context = {
        'form': form,
    }
    return render(request, 'mainapp/scientist_create.html', context)


def scientistsdetails(request, slug):
    question = get_object_or_404(Scientists, slug=slug)
    context = {'scientist': question, 'title': question.name}
    return render(request, 'mainapp/scientistsdetails.html', context)


class ScientistsUpdateView(UpdateView):
    model = Scientists
    template_name = 'mainapp/scientist_create.html'
    form_class = ScientistsForm


class ScientistsDeleteView(DeleteView):
    model = Scientists
    template_name = 'mainapp/scientist-delete.html'
    success_url = '/scientists/'


def scientist_or_dari(request):
    context = {'title': 'Дәрішөп н/е ғалымдар', }
    return render(request, 'mainapp/scientist_or_dari.html', context)


def contact(request):
    form = ReviewForm()
    context = {'title': 'Контактілер', 'form': form}
    return render(request, 'mainapp/contact.html', context)


def addreview(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.save()
            return redirect('home')

templates/mainapp/about.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="zxx">
<head>
    <title>{% block title %}{{ title }}{% endblock title %}</title>


</head>
<body>
{% block content %}
<div id="preloder">
    <div class="loader"></div>
</div>

<!-- Main section start -->
<div class="main-site-warp">
    {% block sidebar %}
    {% include 'include/sidebar.html' %}
    {% endblock sidebar %}

    <div class="site-content-warp">
        {% block left_side %}
        {% include 'include/left_side.html' %}
        {% endblock left_side %}
        <!-- Page start -->
        <div class="page-section about-page">
            <div class="about-section" style="margin-left:30px;">
                <div class="video-section set-bg" data-setbg="{% static 'img/about-bg.jpg' %}" style="width:663px;height:400px;">

                </div>
                <div class="row m-0 milestones">
                    <div class="col-lg-3 col-sm-6 p-0">
                        <div class="milestone">
                            <h2>25</h2>
                            <div class="milestone-info">
                                <h5>жылдан аса тәжірибе</h5>
<!--                                <p>Nature Photography</p>-->
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6 p-0">
                        <div class="milestone">
                            <h2>16k</h2>
                            <div class="milestone-info">
                                <h5>аса зерттеулер</h5>
<!--                                <p>зерттеулер</p>-->
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6 p-0">
                        <div class="milestone">
                            <h2>59</h2>
                            <div class="milestone-info">
                                <h5>зерттеуші</h5>
                                <h5>ғалымдар</h5>
<!--                                <p>Happy Couples</p>-->
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-sm-6 p-0">
                        <div class="milestone">
                            <h2>37k</h2>
                            <div class="milestone-info">
                                <h5>дәрілікшөптер</h5>
<!--                                <p>Thank you</p>-->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Page end -->
    </div>
</div>

{% endblock content %}
</body>
</html>

templates/mainapp/blog.html
<!DOCTYPE html>
<html lang="zxx">
<head>
	<title>NISSA - PHOTOGRAPHY STUDIO HTML TEMPLATE</title>
	<meta charset="UTF-8">
	<meta name="description" content="Nissa Photography studio html template">
	<meta name="keywords" content="industry, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
	<!-- Favicon -->
	<link href="img/favicon.ico" rel="shortcut icon"/>

	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,900&display=swap" rel="stylesheet">

	<!-- Stylesheets -->
	<link rel="stylesheet" href="css/bootstrap.min.css"/>
	<link rel="stylesheet" href="css/font-awesome.min.css"/>
	<link rel="stylesheet" href="css/magnific-popup.css"/>
	<link rel="stylesheet" href="css/owl.carousel.min.css"/>

	<!-- Main Stylesheets -->
	<link rel="stylesheet" href="css/style.css"/>


	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>
<body>
	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>

	<!-- Main section start -->
	<div class="main-site-warp">
		<div class="site-menu-warp">
			<div class="close-menu">x</div>
			<!-- Main menu -->
			<ul class="site-menu">
				<li><a href="index.html">Home</a></li>
				<li><a href="about.html">About Me</a></li>
				<li><a href="blog.html" class="active">Blog</a></li>
				<li><a href="portfolio.html">Portfolio</a></li>
				<li><a href="contact.html">Contact</a></li>
				<li><a href="elements.html">Elements</a></li>
			</ul>
			<div class="menu-social">
				<a href=""><i class="fa fa-pinterest"></i></a>
				<a href=""><i class="fa fa-facebook"></i></a>
				<a href=""><i class="fa fa-twitter"></i></a>
				<a href=""><i class="fa fa-dribbble"></i></a>
				<a href=""><i class="fa fa-behance"></i></a>
			</div>
		</div>
		<header class="header-section">
			<div class="nav-switch">
				<i class="fa fa-bars"></i>
			</div>
			<div class="header-social">
				<a href=""><i class="fa fa-pinterest"></i></a>
				<a href=""><i class="fa fa-facebook"></i></a>
				<a href=""><i class="fa fa-twitter"></i></a>
				<a href=""><i class="fa fa-dribbble"></i></a>
				<a href=""><i class="fa fa-behance"></i></a>
			</div>
		</header>
		<div class="site-content-warp">
			<!-- Left Side section -->
			<div class="main-sidebar">
				<div class="mb-warp">
					<a href="index.html" class="site-logo">
						<h2>Nissa</h2>
						<p>Photography Studio</p>
					</a>
					<div class="about-info">
						<h2>My name is Michael Smith.</h2>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus libero mauris, bibendum eget sapien ac, ultrices rhoncus ipsum. Donec nec sapien in urna fermentum ornare. Morbi vel ultrices leo. Sed eu turpis eu arcu vehicula fringilla ut vitae orci. Suspendisse maximus malesuada  </p>
					</div>
					<ul class="contact-info">
						<li>1525  Boring Lane, Los Angeles, CA</li>
						<li>+34 56672 9984 22</li>
						<li><a href="mailto:contactme@myemail.com">contactme@myemail.com</a></li>
					</ul>
					<a href="#" class="site-btn">see my portfolio <img src="img/arrow-right.png" alt=""></a>
				</div>
			</div>
			<!-- Left Side section end -->
			<!-- Page start -->
			<div class="page-section blog-page">
				<div class="blog-posts">
					<div class="blog-post-item">
						<div class="blog-thumb set-bg" data-setbg="img/blog/1.jpg">
							<div class="post-date">
								<h3>23</h3>
								<p>March<br>2019</p>
							</div>
						</div>
						<div class="blog-content">
							<h2><a href="./single-blog.html">10 Essential photography tips</a></h2>
							<div class="blog-metas">
								<div class="blog-meta">By Michael Smith</div>
								<div class="blog-meta">in Photography</div>
								<div class="blog-meta">2 Comments</div>
							</div>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus libero mauris, bibendum eget sapien ac, ultrices rhoncus ipsum. Donec nec sapien in urna fermentum ornare. Morbi vel ultrices leo. Sed eu turpis eu arcu vehicula fringilla ut vitae orci. Suspendisse maximus malesuada  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus libero mauris, bibendum eget sapien ac, ultrices rhoncus ipsum. Donec nec sapien in urna fermentum ornare. Morbi vel ultrices leo. Sed eu turpis eu arcu vehicula fringilla ut vitae orci. Suspendisse maximus malesuada.  </p>
						</div>
					</div>
					<div class="blog-post-item">
						<div class="blog-thumb set-bg" data-setbg="img/blog/2.jpg">
							<div class="post-date">
								<h3>23</h3>
								<p>March<br>2019</p>
							</div>
						</div>
						<div class="blog-content">
							<h2>10 Essential photography tips</h2>
							<div class="blog-metas">
								<div class="blog-meta">By Michael Smith</div>
								<div class="blog-meta">in Photography</div>
								<div class="blog-meta">2 Comments</div>
							</div>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus libero mauris, bibendum eget sapien ac, ultrices rhoncus ipsum. Donec nec sapien in urna fermentum ornare. Morbi vel ultrices leo. Sed eu turpis eu arcu vehicula fringilla ut vitae orci. Suspendisse maximus malesuada  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus libero mauris, bibendum eget sapien ac, ultrices rhoncus ipsum. Donec nec sapien in urna fermentum ornare. Morbi vel ultrices leo. Sed eu turpis eu arcu vehicula fringilla ut vitae orci. Suspendisse maximus malesuada.  </p>
						</div>
					</div>
				</div>
			</div>
			<!-- Page end -->
		</div>
		<div class="copyright"><p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p></div>
	</div>
	<!-- Main section end -->
	

	
	<!--====== Javascripts & Jquery ======-->
	<script src="js/jquery-3.2.1.min.js"></script>
	<script src="js/bootstrap.min.js"></script>
	<script src="js/owl.carousel.min.js"></script>
	<script src="js/jquery.nicescroll.min.js"></script>
	<script src="js/circle-progress.min.js"></script>
	<script src="js/jquery.magnific-popup.min.js"></script>
	<script src="js/main.js"></script>

	</body>
</html>

templates/mainapp/contact.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="zxx">
<head>
    <title>{% block title %}{{ title }}{% endblock title %}</title>

</head>
<body>
{% block content %}
<!-- Page Preloder -->
<div id="preloder">
    <div class="loader"></div>
</div>

<!-- Main section start -->
<div class="main-site-warp">
    {% block sidebar %}
    {% include 'include/sidebar.html' %}
    {% endblock sidebar %}

    <div class="site-content-warp">
        {% block left_side %}
        {% include 'include/left_side.html' %}
        {% endblock left_side %}
        <!-- Page start -->
        <div class="page-section contact-page">
            <div class="contact-section">
                <div class="row" style="margin-left:50px;">
                    <div class="col-xl-6">
                        <div class="map">

                            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2907.247794266376!2d76.92039181486442!3d43.22526408801571!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38836f18bf548af5%3A0x4eb3eb5eaef8aa6!2z0JrQsNC30LDRhdGB0LrQuNC5INCd0LDRhtC40L7QvdCw0LvRjNC90YvQuSDQo9C90LjQstC10YDRgdC40YLQtdGCINC40LzQtdC90Lgg0JDQu9GMLdCk0LDRgNCw0LHQuA!5e0!3m2!1sru!2skz!4v1653377653297!5m2!1sru!2skz"
                                    style="border:0" allowfullscreen></iframe>
                        </div>
                    </div>
                    <div class="col-xl-6">
                        <div class="contact-text-warp">
                            <div class="contact-text">
                                <h2>Бізбен байланыс</h2>
                                <p>Біз сізге дәрішөптер туралы ақпарат алуға, оларды өңдеуге және мәліметтер қорына қосуға көсектесеміз.</p>
                            </div>
                            <form action="{% url 'addreview' %}" class="contact-form" method="post">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-lg-6">
                                        {{ form.name }}
                                    </div>
                                    <div class="col-lg-6">
                                        {{ form.email }}
                                    </div>
                                    <div class="col-lg-12">
                                        {{ form.title }}
                                        {{ form.text }}
                                        <button type="submit" class="site-btn">Жіберу <img
                                                src="{% static 'img/arrow-right.png' %}" alt="">
                                        </button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Page end -->
    </div>
</div>

{% endblock content %}
</body>
</html>

templates/mainapp/dari_create.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="zxx">
<head>
    <title>{% block title %}{{ title }}{% endblock title %}</title>


</head>
<body>
{% block content %}
<div id="preloder">
    <div class="loader"></div>
</div>

<div class="main-site-warp">
    {% block sidebar %}
    {% include 'include/sidebar.html' %}
    {% endblock sidebar %}

    <div class="site-content-warp">
        {% block left_side %}
        {% include 'include/left_side.html' %}
        {% endblock left_side %}
        <div class="page-section about-page">
            <div class="about-section" style="margin-left:30px;">
                {% autoescape off %}
                <div class="col-xl-6">
                    <div class="contact-text-warp">
                        <div class="contact-text">
                            <h2>Дәрішөп </h2>
                            <!--                                <p>Біз сізге дәрішөптер туралы ақпарат алуға, оларды өңдеуге және мәліметтер қорына қосуға көсектесеміз.</p>-->
                        </div>
                        <form action="{% url 'adddari' %}" class="contact-form" method="post">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-lg-6">
                                    {{ form.name }}
                                </div>
                                <div class="col-lg-6">
                                    {{ form.type }}
                                </div>
                                <div class="col-lg-12">
                                    {{ form.slug }}
                                </div>

                                <div class="col-lg-12">
                                        {{ form.anyqtama }}
                                    </div>
                                    <div class="col-lg-12">
                                        {{ form.description }}
                                    </div>
                                    <div class="col-lg-12">
                                        {{ form.qoldanui }}
                                    </div>
                                    <div class="col-lg-12">
                                        {{ form.count }}
                                    </div>
                                    <div class="col-lg-12">
                                        {{ form.scientists }}
                                    </div>
                                    <div class="col-lg-12">
                                        <br>
                                        {{ form.region }}
                                         <br>
                                    </div>
                                    <div class="col-lg-12">
                                        {{ form.image }}
                                        <button type="submit" class="site-btn">Жіберу <img
                                                src="{% static 'img/arrow-right.png' %}" alt="">
                                        </button>
                                    </div>


                            </div>
                        </form>
                    </div>
                </div>
                {% endautoescape %}
            </div>
        </div>
    </div>
    <br>
    <br>
</div>

{% endblock content %}
</body>
</html>

templates/mainapp/dariler-delete.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="zxx">
<head>
    <title>{% block title %}{{ title }}{% endblock title %}</title>


</head>
<body>
{% block content %}
<div id="preloder">
    <div class="loader"></div>
</div>

<div class="main-site-warp">
    {% block sidebar %}
    {% include 'include/sidebar.html' %}
    {% endblock sidebar %}

    <div class="site-content-warp">
        {% block left_side %}
        {% include 'include/left_side.html' %}
        {% endblock left_side %}
        <div class="page-section about-page">
            <div class="about-section" style="margin-left:30px;">
                <div class="features">
                    <h3 style="margin-left:30px;">Дәрішөпті өшіру</h3>
                    <form method="post">
                        {% csrf_token %}
                        <br>
                        <br>
                        <button class="btn btn-success" style="margin-left:30px;" type="submit">Өшіру</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <br>
    <br>
</div>

{% endblock content %}
</body>
</html>

templates/mainapp/scientistsdetails.html
{% extends 'base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="zxx">
<head>
    <title>{% block title %}{{ title }}{% endblock title %}</title>


</head>
<body>
{% block content %}
<div id="preloder">
    <div class="loader"></div>
</div>

<div class="main-site-warp">
    {% block sidebar %}
    {% include 'include/sidebar.html' %}
    {% endblock sidebar %}

    <div class="site-content-warp">
        {% block left_side %}
        {% include 'include/left_side.html' %}
        {% endblock left_side %}
        <h3 style="margin-left:30px;">{{ scientist.name }} {{ scientist.surname }}</h3>
        <br>
        {% if scientist.image %}
        <img style="margin-left:30px;" src="{{ scientist.image.url }}"
             height="400px" width="300px" alt="">
        {% endif %}
        <br>
        <br>
        <div style="margin-left:30px;">
            <p><h4>Лауазымы: </h4>{{ scientist.lauazym }}<br><br>
            <h4>Айналысу саласы: </h4>{{ scientist.ainalasu_salasy }}<br><br>
            <h4>Зерттеген дәрілер: </h4>
            {% for d in scientist.darishopter_set.all %}
            <a href="{% url 'daridetails' d.slug %}"> {{ d.name }} <br></a>

            {% endfor %}
            <br>
            {% if user.is_authenticated %}
            <a href="{% url 'scientists-update' scientist.slug %}"
               class="btn btn-info">Өңдеу</a>

            <a href="{% url 'scientists-delete' scientist.slug %}" class="btn btn-danger">Өшіру</a>
            <a href="{% url 'scientist-create' %}" class="btn btn-primary">Ғалымдар
                қосу</a>
            {% endif %}
            <br>
        </div>
    </div>
</div>
{% endblock content %}
</body>
</html>